In [21]:
import numpy as np
import pandas as pd

In [22]:
data=pd.read_csv('Dataset.csv')
data

Loan Identifier  Monthly Reporting Period  Channel  \
0           100007365142                     12000        2   
1           100007365142                     22000        2   
2           100007365142                     32000        2   
3           100007365142                     42000        2   
4           100007365142                     52000        2   
...                  ...                       ...      ...   
1256463        105675700                    112021        2   
1256464        105675700                    122021        2   
1256465        105675700                     12022        2   
1256466        105675700                     22022        2   
1256467        105675700                     32022        2   

         Original Interest Rate  Current Interest Rate  Original UPB  \
0                         8.000                  8.000       75000.0   
1                         8.000                  8.000       75000.0   
2                         8.000                  8.000       75000.0   
3                         8.000                  8.000       75000.0   
4                         8.000                  8.000       75000.0   
...                         ...                    ...           ...   
1256463                   3.062                  3.062      510000.0   
1256464                   3.062                  3.062      510000.0   
1256465                   3.062                  3.062      510000.0   
1256466                   3.062                  3.062      510000.0   
1256467                   3.062                  0.000      510000.0   

         Current Actual UPB  Original Loan Term  Origination Date  \
0                  75000.00                 360            121999   
1                  75000.00                 360            121999   
2                  75000.00                 360            121999   
3                  75000.00                 360            121999   
4                  75000.00                 360            121999   
...                     ...                 ...               ...   
1256463           500744.85                 360            112020   
1256464           499853.61                 360            112020   
1256465           498960.10                 360            112020   
1256466           498064.31                 360            112020   
1256467                0.00                 360            112020   

         First Payment Date  ...  High Balance Loan Indicator  \
0                     22000  ...                            0   
1                     22000  ...                            0   
2                     22000  ...                            0   
3                     22000  ...                            0   
4                     22000  ...                            0   
...                     ...  ...                          ...   
1256463               12021  ...                            0   
1256464               12021  ...                            0   
1256465               12021  ...                            0   
1256466               12021  ...                            0   
1256467               12021  ...                            0   

         Unemployment_rate  Divorce_rate  Inflation_rate          EMI  \
0                      4.0           4.0             2.7   550.323430   
1                      4.0           4.0             3.2   550.323430   
2                      4.0           4.0             3.8   550.323430   
3                      4.0           4.0             3.1   550.323430   
4                      4.0           4.0             3.2   550.323430   
...                    ...           ...             ...          ...   
1256463                5.3           2.5             6.8  2167.271522   
1256464                5.3           2.5             7.0  2167.271522   
1256465                3.6           2.3             7.5  2167.271522   
1256466                3.6           2.3       

In [23]:
X=data.drop(['Remaining Months To Maturity','Current Actual UPB','EMI',
       'UPB_diff', 'Interest_Component', 'PREPAYMENT_AMT'],axis=1)

In [24]:
y=data['Current Actual UPB']

In [25]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [26]:
from sklearn.ensemble import GradientBoostingRegressor

gbr = GradientBoostingRegressor(subsample = 0.9, 
                                max_features = 0.75,
                                random_state = 42,
                                warm_start = True,
                                learning_rate= 0.01)

gbr.fit(X_train,y_train)


GradientBoostingRegressor(learning_rate=0.01, max_features=0.75,
                          random_state=42, subsample=0.9, warm_start=True)

In [27]:
gbr_y_pred=gbr.predict(X_test)

In [28]:
gbr_y_pred

array([128940.23730784, 115222.53693432, 326096.65163471, ...,
       111367.52040402, 176768.42573154, 218790.57424976])

In [29]:
y_test

598697     107705.52
553262      83176.97
1049142    435427.40
833138     241000.00
640177      54191.96
             ...    
1134434    177734.69
285317      55892.06
405782      77622.09
565714     190255.82
286399     230880.97
Name: Current Actual UPB, Length: 251294, dtype: float64

In [11]:
import lightgbm as lgb
from sklearn.metrics import mean_squared_error

# Define the LightGBM dataset
train_data = lgb.Dataset(X_train, label=y_train)

# Set the hyperparameters for the LightGBM model
params = {
    'boosting_type': 'gbdt',
    'objective': 'regression',
    'metric': 'mse',
    'num_leaves': 31,
    'learning_rate': 0.05,
    'feature_fraction': 0.9,
    'bagging_fraction': 0.8,
    'bagging_freq': 5,
    'verbose': 0
}

# Train the LightGBM model
model = lgb.train(params, train_data, num_boost_round=100)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] Auto-choosing row-wise multi-threading, the overhead of testing was 0.122494 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
Mean Squared Error: 10454298.061704272


In [12]:
y_pred

array([176041.60004188,  15917.88948596, 335004.15329398, ...,
        89001.05352498, 220430.78685206,  54281.2646137 ])

In [13]:
y_test

646999     174311.65
639890      14210.38
978958     333024.10
719201     157225.47
286085     132689.44
             ...    
1136839    213753.53
346801     115431.35
594680      88523.97
347727     220805.96
559828      54039.19
Name: Current Actual UPB, Length: 251294, dtype: float64

In [16]:
import pickle as pkl

file = open("Random forest.sav", 'rb')
rfr=pkl.load(file)

c:\Python10\lib\site-packages\sklearn\base.py:299: UserWarning: Trying to unpickle estimator DecisionTreeRegressor from version 1.2.2 when using version 1.2.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\Python10\lib\site-packages\sklearn\base.py:299: UserWarning: Trying to unpickle estimator RandomForestRegressor from version 1.2.2 when using version 1.2.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(


In [ ]:
from sklearn.ensemble import VotingRegressor

voting_reg = VotingRegressor(
    estimators=[('svr',best_model_svr),('xgb',XG)])

In [18]:
rfr_y_pred=rfr.predict(X_test.drop(['Zero Balance Code'],axis=1))

In [19]:
rfr_y_pred

array([174247.8122,  14162.9025, 333030.2553, ...,  88692.609 ,
       220789.4986,  54040.0222])

In [20]:
y_test

646999     174311.65
639890      14210.38
978958     333024.10
719201     157225.47
286085     132689.44
             ...    
1136839    213753.53
346801     115431.35
594680      88523.97
347727     220805.96
559828      54039.19
Name: Current Actual UPB, Length: 251294, dtype: float64

In [32]:
from sklearn.metrics import mean_squared_error
mean_squared_error(rfr_y_pred,y_test)

24566610611.58351

In [30]:
import pickle

with open('elasnet.pkl', 'rb') as f:
    clf2 = pickle.load(f)


In [31]:
elas_predict=clf2.predict(X_test)

c:\Python10\lib\site-packages\sklearn\base.py:413: UserWarning: X has feature names, but ElasticNet was fitted without feature names
  warnings.warn(


ValueError: X has 31 features, but ElasticNet is expecting 527 features as input.